//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HekkaDAQ.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HekkaDAQ.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller
        ///[
        ///	Clock &quot;Clock&quot;
        ///	
        ///	DAQController &quot;Heka,Heka.HekaDAQController,&quot;
        ///	[
        ///		Provides Clock &quot;Clock&quot;
        ///		Clock &quot;Clock&quot;
        ///		Configuration
        ///		[
        ///			DeviceType &quot;1&quot;
        ///			DeviceNumber &quot;0&quot;
        ///		]
        ///		InputStream &quot;ai0&quot; &quot;Heka.HekaDAQInputStream&quot;
        ///		[
        ///			Clock &quot;Clock&quot;
        ///			Configuration
        ///			[
        ///				MeasurementConversionTarget &quot;V&quot;
        ///			]
        ///			SampleRate 1000 Hz
        ///		]
        ///		OutputStream &quot;ao0&quot; &quot;Heka.HekaDAQOutputStream&quot;
        ///		[
        ///			Clock &quot;Clock&quot;
        ///			Configuration
        ///			[
        ///				MeasurementConversionTarget &quot;V&quot;
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BasicConfig {
            get {
                return ResourceManager.GetString("BasicConfig", resourceCulture);
            }
        }
    }
}
